### ISSUE TITLE
bug : Content button link name is wrong. deprem.şo

### ISSUE THREAD

**Issue by ghost** [acikyazilimagi/afet-org.old#9]
##  Bug Definition
Link name is deprem.şo

** discord username: @hitayco**

## Bug environment
afet.org

##  Describe how you are producing the bug step by step
1.Go to ['this link'](https://afet.org/)
2.Look at the Website content buttons
3.Link name is deprem.şo

## Expected Behaviour
Link name should be deprem.io

##  Screen shots
<img width="778" alt="Screen Shot 2023-02-11 at 12 59 09" src="https://user-images.githubusercontent.com/107373502/218252338-869f1608-c892-42e7-a1bd-68af28d3eba8.png">

##  Desktop Information
doesn't matter

##  Mobile Phone Information
doesn't matter

## Additional Context
no more

**Comment by VictorTomaili** [comment]
#8 active pr

**Comment by hmert** [comment]
thanks a lot, fixed now.
